services:
  - type: web
    name: self-checkout-api
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y portaudio19-dev libasound-dev libffi-dev build-essential && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    region: oregon  # or your preferred region
    plan: free

